<IMG WIDTH=100 ALIGN=LEFT SRC=/images/stk-logo.png><H1>The Sequence Toolkit Web Monitor</H1><div id="generated_date" style='padding:10px 10px; text-align: right'></div>
<HR WIDTH=100%>
<script>
function change_bg (id,col) { var element = document.getElementById(id); element.style.background = col; }
</script>
<style> 
.buttondiv { border:2px solid #444444; padding:5px 40px; background:#22cccc; width:200px; border-radius:20px; -moz-border-radius:20px; /* Old Firefox */; text-align:center }
</style>
<TABLE ALIGN=RIGHT><TR>
<TD><div class=buttondiv id=services_button onmouseover="change_bg('services_button','#aaaaaa')" onmouseout="change_bg('services_button','#22cccc')" onclick="javascript:document.location='/services';"><B>Services</B></div></TD>
<TD><div class=buttondiv id=groups_button onmouseover="change_bg('groups_button','#aaaaaa')" onmouseout="change_bg('groups_button','#22cccc')" onclick="javascript:document.location='/service_groups';"><B>Service Groups</B></div></TD>
</TR></TABLE><BR CLEAR=ALL>


