<STYLE>
.chart { background: #b0e0f8; margin: 5px; }
.chart rect { stroke: white; fill: steelblue; }
.chart text { fill: white; }
.chart text.name { fill: #000; }
</STYLE>

<script src="/js/d3.v3.min.js"  charset="utf-8"></script>

<!-- These div's are used to generate the html for the charts and are then copied -->
<div id="chart" class="chart" hidden></div>
<div id="history_chart" class="chart" hidden></div>

<script src="/js/stkcharts.js"></script>
