<HTML><script src="/js/stkhttpd.js"></script>
<HEAD><TITLE>Sequence Toolkit Web Interface</TITLE>
<meta http-equiv="Content-type" content="text/html;charset=UTF-8;">
</HEAD>
<BODY background=/images/greybg.png bgcolor=#aaaaaa>
<STYLE>H1 {margin-top: 5px; margin-bottom: 5px; text-align: CENTER; COLOR: #000000}</STYLE>
<STYLE>H2 {margin-top: 5px; margin-bottom: 5px; COLOR: #000000}</STYLE>
<div style='background-color:#cccccc; background-image:url(/images/lightgreybg.png)'>

