<HTML>
<HEAD><TITLE>Sequence Toolkit Web Interface</TITLE>
<meta http-equiv="Content-type" content="text/html;charset=UTF-8;">
<script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="/js/stkhttpd.js"></script>
</HEAD>
<BODY background=/images/greybg.png bgcolor=#aaaaaa>
<STYLE>H1 {margin-top: 5px; margin-bottom: 5px; text-align: CENTER; COLOR: #000000}</STYLE>
<STYLE>H2 {margin-top: 5px; margin-bottom: 5px; COLOR: #000000}</STYLE>
<div style='background-color:#cccccc; background-image:url(/images/lightgreybg.png)'>
